//! In-place write-through DOM handles over the canonical Rust `Hcdf`, GENERATED by the
//! `hcdformat-pyderive` proc-macro (`#[pydom]`) for the WHOLE ~190-type model. This module holds the
//! shared runtime the generated code relies on, wires in the generated mirrors, and hand-writes the
//! irregular named-field `VisualAppearance` companion. Generic tuple tagged choices are generated.
//!
//! MODEL:
//!   * One owner holds `Rc<RefCell<Root>>`; all methods borrow it transiently.
//!   * Sub-handles carry a `Py<Owner>` plus a per-type locator ([`Resolve::Loc`]); no Rust reference
//!     points into the document.
//!   * Every read/write borrows transiently under the GIL, navigates by locator, mutates, drops.
//!
//! DAG: a shared type is reachable from many parents, so its locator is an ENUM (one variant per parent
//! site) and the single `impl Resolve` matches over it. `dom_generated.rs` (emitted by `hcdformat-domgen`
//! from the model AST, drift-checked in CI) declares one `#[pydom]` mirror per reachable struct; the
//! macro expands each into its handle. See `hcdformat-pyderive/src/lib.rs`.

use hcdformat::model::{Visual, VisualAppearance, VisualGeometry};
use hcdformat::{Hcdf, StreamProfileDocument};
use pyo3::exceptions::PyValueError;
use pyo3::prelude::*;

#[path = "dom_generated.rs"]
mod generated;
pub(crate) use generated::PyHcdf;
use generated::PyVisualLoc;

#[path = "stream_profile_dom_generated.rs"]
mod stream_profile_generated;
pub(crate) use stream_profile_generated::PyStreamProfileDocument;

/// Build a fresh root DOM handle owning `doc`. The module-level `hcdf.dom.load`/`loads` and the
/// URDF/SDF importers use this to hand a freshly built document back to Python as an `Hcdf` handle.
pub(crate) fn new_handle(doc: Hcdf) -> PyHcdf {
    PyHcdf {
        doc: std::rc::Rc::new(std::cell::RefCell::new(doc)),
    }
}

pub(crate) fn new_stream_profile_handle(doc: StreamProfileDocument) -> PyStreamProfileDocument {
    PyStreamProfileDocument {
        doc: std::rc::Rc::new(std::cell::RefCell::new(doc)),
    }
}

/// Serialize a root handle's document to canonical XML, the natural interchange the surface hands the
/// core (`hcdf.dom.dumps`, and the string boundary the JSON and bundle helpers cross).
pub(crate) fn handle_xml(h: &PyHcdf) -> PyResult<String> {
    h.doc.borrow().to_xml_string().map_err(err)
}

pub(crate) fn stream_profile_handle_xml(h: &PyStreamProfileDocument) -> PyResult<String> {
    h.doc.borrow().to_xml_string().map_err(err)
}

// ── shared runtime support the generated code relies on ─────────────────────────────────────────

/// Map any crate error into a Python `ValueError`.
fn err<E: std::fmt::Display>(e: E) -> PyErr {
    PyValueError::new_err(e.to_string())
}

/// A locator that no longer resolves (the Vec shrank under it, or an Option was cleared) surfaces as a
/// clear Python error rather than a panic, the KNOWN weakness of index locators (append is safe).
fn stale(what: &str) -> PyErr {
    PyValueError::new_err(format!("stale handle: {what} no longer resolves"))
}

/// Normalize a possibly-negative Python index against `len`.
fn resolve_index(idx: isize, len: usize) -> PyResult<usize> {
    let i = if idx < 0 { idx + len as isize } else { idx };
    if i < 0 || i as usize >= len {
        return Err(PyValueError::new_err(format!(
            "index {idx} out of range (len {len})"
        )));
    }
    Ok(i as usize)
}

/// Navigate an owned root to a typed node by its locator. The macro implements this local trait for
/// model types. Each model type has one implementation per owner root; a shared type's `Loc` is an
/// enum over its parent sites. The chain is transient, so no borrow outlives a single Python call.
pub trait Resolve<Root>: Sized {
    type Loc;
    fn resolve<'a>(root: &'a Root, loc: &Self::Loc) -> Option<&'a Self>;
    fn resolve_mut<'a>(root: &'a mut Root, loc: &Self::Loc) -> Option<&'a mut Self>;
}

// Category 7 explicit companion: the irregular named-field `VisualAppearance` choice.
//
// `VisualAppearance` is an untagged xs:choice of two payload-bearing arms
// (Model{model, geometry} | Primitive{geometry, color}). Its named-field arms require a purpose-built
// Python surface, while generic tuple tagged choices use generated variant-aware handles. This
// companion also reaches the two types that live only inside these arms (`ModelRef` via
// model_uri/model_sha; the inline `Color` via color_*), which have no struct-field site of their own.
// `VisualGeometry` (the primitive/fallback `<geometry>` that lives inside BOTH arms) is likewise reached
// through the choice: `geometry_kind` + `set_geometry(kind)` select the active primitive and the
// `geometry_size`/`_radius`/`_length`/`_radii` accessors read/write its dims (variant-aware, mirroring
// the color_* pattern). With that, no leaf of the appearance choice is left un-navigable.

/// Variant-aware handle over `visual.appearance`. Exposes the active variant and its scalar payload.
#[pyclass(unsendable, name = "PyVisualAppearance")]
pub struct PyVisualAppearance {
    pub(crate) owner: Py<PyHcdf>,
    pub(crate) loc: PyVisualLoc,
}

impl PyVisualAppearance {
    fn with<R>(&self, py: Python<'_>, f: impl FnOnce(&Visual) -> PyResult<R>) -> PyResult<R> {
        let owner = self.owner.borrow(py);
        let doc = owner.doc.borrow();
        let v =
            <Visual as Resolve<Hcdf>>::resolve(&doc, &self.loc).ok_or_else(|| stale("PyVisual"))?;
        f(v)
    }
    fn with_mut<R>(
        &self,
        py: Python<'_>,
        f: impl FnOnce(&mut Visual) -> PyResult<R>,
    ) -> PyResult<R> {
        let owner = self.owner.borrow(py);
        let mut doc = owner.doc.borrow_mut();
        let v = <Visual as Resolve<Hcdf>>::resolve_mut(&mut doc, &self.loc)
            .ok_or_else(|| stale("PyVisual"))?;
        f(v)
    }
}

#[pymethods]
impl PyVisualAppearance {
    /// The active arm of the choice: `"model"` or `"primitive"`.
    #[getter]
    fn variant(&self, py: Python<'_>) -> PyResult<String> {
        self.with(py, |v| {
            Ok(match &v.appearance {
                VisualAppearance::Model { .. } => "model".to_string(),
                VisualAppearance::Primitive { .. } => "primitive".to_string(),
            })
        })
    }

    /// Switch to the ARM A (`model`) variant, resetting its payload to empty defaults.
    fn set_model(&self, py: Python<'_>) -> PyResult<()> {
        self.with_mut(py, |v| {
            v.appearance = VisualAppearance::Model {
                model: Default::default(),
                geometry: None,
            };
            Ok(())
        })
    }

    /// Switch to the ARM B (`primitive`) variant, resetting its payload to empty defaults.
    fn set_primitive(&self, py: Python<'_>) -> PyResult<()> {
        self.with_mut(py, |v| {
            v.appearance = VisualAppearance::Primitive {
                geometry: None,
                color: None,
            };
            Ok(())
        })
    }

    /// `model/@uri`: readable/writable only while the active variant is `model`.
    #[getter]
    fn get_model_uri(&self, py: Python<'_>) -> PyResult<Option<String>> {
        self.with(py, |v| match &v.appearance {
            VisualAppearance::Model { model, .. } => Ok(model.uri.clone()),
            VisualAppearance::Primitive { .. } => Err(PyValueError::new_err(
                "model_uri: active variant is 'primitive'",
            )),
        })
    }
    #[setter]
    fn set_model_uri(&self, py: Python<'_>, val: Option<String>) -> PyResult<()> {
        self.with_mut(py, |v| match &mut v.appearance {
            VisualAppearance::Model { model, .. } => {
                model.uri = val;
                Ok(())
            }
            VisualAppearance::Primitive { .. } => Err(PyValueError::new_err(
                "model_uri: switch to the 'model' variant first (set_model())",
            )),
        })
    }

    /// `model/@sha`: readable/writable only while the active variant is `model`.
    #[getter]
    fn get_model_sha(&self, py: Python<'_>) -> PyResult<Option<String>> {
        self.with(py, |v| match &v.appearance {
            VisualAppearance::Model { model, .. } => Ok(model.sha.clone()),
            VisualAppearance::Primitive { .. } => Err(PyValueError::new_err(
                "model_sha: active variant is 'primitive'",
            )),
        })
    }
    #[setter]
    fn set_model_sha(&self, py: Python<'_>, val: Option<String>) -> PyResult<()> {
        self.with_mut(py, |v| match &mut v.appearance {
            VisualAppearance::Model { model, .. } => {
                model.sha = val;
                Ok(())
            }
            VisualAppearance::Primitive { .. } => Err(PyValueError::new_err(
                "model_sha: switch to the 'model' variant first (set_model())",
            )),
        })
    }

    /// `color/@rgba` on the ARM B inline color, readable/writable only while the active variant is
    /// `primitive`. Reaches `Color` (which otherwise lives only inside this arm). Absent color reads as
    /// `None`; setting a value materializes the inline `<color>` if needed.
    #[getter]
    fn get_color_rgba(&self, py: Python<'_>) -> PyResult<Option<String>> {
        self.with(py, |v| {
            primitive_color(v, |c| c.and_then(|c| c.rgba.clone()))
        })
    }
    #[setter]
    fn set_color_rgba(&self, py: Python<'_>, val: Option<String>) -> PyResult<()> {
        self.with_mut(py, |v| primitive_color_mut(v, |c| c.rgba = val))
    }

    /// `color/@name` on the ARM B inline color (see [`get_color_rgba`]).
    #[getter]
    fn get_color_name(&self, py: Python<'_>) -> PyResult<Option<String>> {
        self.with(py, |v| {
            primitive_color(v, |c| c.and_then(|c| c.name.clone()))
        })
    }
    #[setter]
    fn set_color_name(&self, py: Python<'_>, val: Option<String>) -> PyResult<()> {
        self.with_mut(py, |v| primitive_color_mut(v, |c| c.name = val))
    }

    /// `color/@description` on the ARM B inline color (see [`get_color_rgba`]).
    #[getter]
    fn get_color_description(&self, py: Python<'_>) -> PyResult<Option<String>> {
        self.with(py, |v| {
            primitive_color(v, |c| c.and_then(|c| c.description.clone()))
        })
    }
    #[setter]
    fn set_color_description(&self, py: Python<'_>, val: Option<String>) -> PyResult<()> {
        self.with_mut(py, |v| primitive_color_mut(v, |c| c.description = val))
    }

    // ── the primitive/fallback `<geometry>` reached THROUGH the choice (present in both arms) ─────────

    /// Active primitive of the appearance's `<geometry>`: `"box"`/`"cylinder"`/`"sphere"`/`"capsule"`/
    /// `"cone"`/`"ellipsoid"`, or `None` when there is no geometry (or an empty one). Works in either arm.
    #[getter]
    fn geometry_kind(&self, py: Python<'_>) -> PyResult<Option<String>> {
        self.with(py, |v| {
            Ok(appearance_geometry(v)
                .and_then(geom_kind)
                .map(str::to_string))
        })
    }

    /// Select the primitive shape of the appearance's `<geometry>`, materializing an empty `<geometry>`
    /// with the chosen child (dims default to absent). `None` clears the geometry. Reaches whichever arm
    /// is active; both `Model` (fallback) and `Primitive` carry `geometry`.
    #[pyo3(signature = (kind=None))]
    fn set_geometry(&self, py: Python<'_>, kind: Option<String>) -> PyResult<()> {
        self.with_mut(py, |v| {
            let slot = geometry_slot_mut(v);
            match kind.as_deref() {
                None => *slot = None,
                Some(k) => {
                    let mut g = VisualGeometry::default();
                    match k {
                        "box" => g.box_ = Some(Default::default()),
                        "cylinder" => g.cylinder = Some(Default::default()),
                        "sphere" => g.sphere = Some(Default::default()),
                        "capsule" => g.capsule = Some(Default::default()),
                        "cone" => g.cone = Some(Default::default()),
                        "ellipsoid" => g.ellipsoid = Some(Default::default()),
                        other => {
                            return Err(PyValueError::new_err(format!(
                                "set_geometry: unknown primitive kind {other:?} \
                                 (expected box/cylinder/sphere/capsule/cone/ellipsoid)"
                            )))
                        }
                    }
                    *slot = Some(g);
                }
            }
            Ok(())
        })
    }

    /// `<box><size>`: valid only while the active geometry primitive is a `box`.
    #[getter]
    fn get_geometry_size(&self, py: Python<'_>) -> PyResult<Option<String>> {
        self.with(py, |v| {
            match appearance_geometry(v).and_then(|g| g.box_.as_ref()) {
                Some(b) => Ok(b.size.clone()),
                None => Err(geom_wrong("geometry_size", "box")),
            }
        })
    }
    #[setter]
    fn set_geometry_size(&self, py: Python<'_>, val: Option<String>) -> PyResult<()> {
        self.with_mut(py, |v| {
            match geometry_slot_mut(v).as_mut().and_then(|g| g.box_.as_mut()) {
                Some(b) => {
                    b.size = val;
                    Ok(())
                }
                None => Err(geom_wrong("geometry_size", "box")),
            }
        })
    }

    /// `<radius>`: valid while the active primitive is `cylinder`/`sphere`/`capsule`/`cone`.
    #[getter]
    fn get_geometry_radius(&self, py: Python<'_>) -> PyResult<Option<String>> {
        self.with(py, |v| {
            let g = appearance_geometry(v).ok_or_else(|| geom_none("geometry_radius"))?;
            if let Some(c) = &g.cylinder {
                Ok(c.radius.clone())
            } else if let Some(s) = &g.sphere {
                Ok(s.radius.clone())
            } else if let Some(c) = &g.capsule {
                Ok(c.radius.clone())
            } else if let Some(c) = &g.cone {
                Ok(c.radius.clone())
            } else {
                Err(geom_wrong(
                    "geometry_radius",
                    "cylinder/sphere/capsule/cone",
                ))
            }
        })
    }
    #[setter]
    fn set_geometry_radius(&self, py: Python<'_>, val: Option<String>) -> PyResult<()> {
        self.with_mut(py, |v| {
            let g = geometry_slot_mut(v)
                .as_mut()
                .ok_or_else(|| geom_none("geometry_radius"))?;
            if let Some(c) = &mut g.cylinder {
                c.radius = val;
            } else if let Some(s) = &mut g.sphere {
                s.radius = val;
            } else if let Some(c) = &mut g.capsule {
                c.radius = val;
            } else if let Some(c) = &mut g.cone {
                c.radius = val;
            } else {
                return Err(geom_wrong(
                    "geometry_radius",
                    "cylinder/sphere/capsule/cone",
                ));
            }
            Ok(())
        })
    }

    /// `<length>`: valid while the active primitive is `cylinder`/`capsule`/`cone`.
    #[getter]
    fn get_geometry_length(&self, py: Python<'_>) -> PyResult<Option<String>> {
        self.with(py, |v| {
            let g = appearance_geometry(v).ok_or_else(|| geom_none("geometry_length"))?;
            if let Some(c) = &g.cylinder {
                Ok(c.length.clone())
            } else if let Some(c) = &g.capsule {
                Ok(c.length.clone())
            } else if let Some(c) = &g.cone {
                Ok(c.length.clone())
            } else {
                Err(geom_wrong("geometry_length", "cylinder/capsule/cone"))
            }
        })
    }
    #[setter]
    fn set_geometry_length(&self, py: Python<'_>, val: Option<String>) -> PyResult<()> {
        self.with_mut(py, |v| {
            let g = geometry_slot_mut(v)
                .as_mut()
                .ok_or_else(|| geom_none("geometry_length"))?;
            if let Some(c) = &mut g.cylinder {
                c.length = val;
            } else if let Some(c) = &mut g.capsule {
                c.length = val;
            } else if let Some(c) = &mut g.cone {
                c.length = val;
            } else {
                return Err(geom_wrong("geometry_length", "cylinder/capsule/cone"));
            }
            Ok(())
        })
    }

    /// `<ellipsoid><radii>`: valid only while the active primitive is an `ellipsoid`.
    #[getter]
    fn get_geometry_radii(&self, py: Python<'_>) -> PyResult<Option<String>> {
        self.with(py, |v| {
            match appearance_geometry(v).and_then(|g| g.ellipsoid.as_ref()) {
                Some(e) => Ok(e.radii.clone()),
                None => Err(geom_wrong("geometry_radii", "ellipsoid")),
            }
        })
    }
    #[setter]
    fn set_geometry_radii(&self, py: Python<'_>, val: Option<String>) -> PyResult<()> {
        self.with_mut(py, |v| {
            match geometry_slot_mut(v)
                .as_mut()
                .and_then(|g| g.ellipsoid.as_mut())
            {
                Some(e) => {
                    e.radii = val;
                    Ok(())
                }
                None => Err(geom_wrong("geometry_radii", "ellipsoid")),
            }
        })
    }
}

/// The appearance's `<geometry>` (shared by both choice arms), read-only.
fn appearance_geometry(v: &Visual) -> Option<&VisualGeometry> {
    match &v.appearance {
        VisualAppearance::Model { geometry, .. } => geometry.as_ref(),
        VisualAppearance::Primitive { geometry, .. } => geometry.as_ref(),
    }
}

/// The appearance's `<geometry>` slot (shared by both choice arms), mutable, for materialize/clear.
fn geometry_slot_mut(v: &mut Visual) -> &mut Option<VisualGeometry> {
    match &mut v.appearance {
        VisualAppearance::Model { geometry, .. } => geometry,
        VisualAppearance::Primitive { geometry, .. } => geometry,
    }
}

/// Which primitive of a `VisualGeometry` is populated (the primitives are mutually exclusive in valid docs).
fn geom_kind(g: &VisualGeometry) -> Option<&'static str> {
    if g.box_.is_some() {
        Some("box")
    } else if g.cylinder.is_some() {
        Some("cylinder")
    } else if g.sphere.is_some() {
        Some("sphere")
    } else if g.capsule.is_some() {
        Some("capsule")
    } else if g.cone.is_some() {
        Some("cone")
    } else if g.ellipsoid.is_some() {
        Some("ellipsoid")
    } else {
        None
    }
}

/// Error when a dim accessor is used against a shape that lacks that dimension.
fn geom_wrong(attr: &str, want: &str) -> PyErr {
    PyValueError::new_err(format!(
        "{attr}: active geometry primitive is not {want} (use set_geometry(...) to select one)"
    ))
}

/// Error when a dim accessor is used but no `<geometry>` is present at all.
fn geom_none(attr: &str) -> PyErr {
    PyValueError::new_err(format!(
        "{attr}: no <geometry> set (call set_geometry(kind) first)"
    ))
}

/// Read the ARM B inline color, erroring if the active variant is `model`.
fn primitive_color<R>(
    v: &Visual,
    f: impl FnOnce(Option<&hcdformat::model::Color>) -> R,
) -> PyResult<R> {
    match &v.appearance {
        VisualAppearance::Primitive { color, .. } => Ok(f(color.as_ref())),
        VisualAppearance::Model { .. } => {
            Err(PyValueError::new_err("color_*: active variant is 'model'"))
        }
    }
}

/// Edit the ARM B inline color in place (materializing an empty `<color>` first), erroring on `model`.
fn primitive_color_mut(
    v: &mut Visual,
    f: impl FnOnce(&mut hcdformat::model::Color),
) -> PyResult<()> {
    match &mut v.appearance {
        VisualAppearance::Primitive { color, .. } => {
            f(color.get_or_insert_with(Default::default));
            Ok(())
        }
        VisualAppearance::Model { .. } => Err(PyValueError::new_err(
            "color_*: switch to the 'primitive' variant first (set_primitive())",
        )),
    }
}

// ── .pyi generation (header + macro-emitted per-type stubs + the companion) ─────────────────────────

/// The full text of `hcdf/dom.pyi`: the header, the public module functions (`load`/`loads`/`dumps`/
/// `dump`), the whole generated DOM (every handle + list sub-handle + the `PyVisualAppearance`
/// companion), and the `Hcdf` public alias of the root handle. Written by the `gen_pyi` bin and
/// byte-checked by the drift test.
pub fn dom_pyi_text() -> String {
    let mut s = format!(
        "{header}from typing import Iterator, Optional\n\n\
         def load(path: str) -> \"PyHcdf\": ...\n\
         def loads(text: object) -> \"PyHcdf\": ...\n\
         def dumps(doc: \"PyHcdf\") -> str: ...\n\
         def dump(doc: \"PyHcdf\", path: str) -> None: ...\n\
         def load_stream_profile(path: str) -> \"PyStreamProfileDocument\": ...\n\
         def loads_stream_profile(text: object) -> \"PyStreamProfileDocument\": ...\n\
         def dumps_stream_profile(doc: \"PyStreamProfileDocument\") -> str: ...\n\
         def dump_stream_profile(doc: \"PyStreamProfileDocument\", path: str) -> None: ...\n\n",
        header = crate::pyi_header(),
    );
    s.push_str(&dom_classes());
    s.push_str("\nHcdf = PyHcdf\nStreamProfileDocument = PyStreamProfileDocument\n");
    s
}

/// The DOM class stubs (every generated handle + list sub-handle + the companion), WITHOUT a header.
pub fn dom_classes() -> String {
    let mut s = generated::pyi_generated();
    s.push_str(&stream_profile_generated::pyi_generated());
    s.push_str(
        "class PyVisualAppearance:\n\
         \x20   variant: str\n\
         \x20   model_uri: Optional[str]\n\
         \x20   model_sha: Optional[str]\n\
         \x20   color_rgba: Optional[str]\n\
         \x20   color_name: Optional[str]\n\
         \x20   color_description: Optional[str]\n\
         \x20   geometry_kind: Optional[str]\n\
         \x20   geometry_size: Optional[str]\n\
         \x20   geometry_radius: Optional[str]\n\
         \x20   geometry_length: Optional[str]\n\
         \x20   geometry_radii: Optional[str]\n\
         \x20   def set_model(self) -> None: ...\n\
         \x20   def set_primitive(self) -> None: ...\n\
         \x20   def set_geometry(self, kind: Optional[str]) -> None: ...\n",
    );
    s
}

/// The generated DOM stub text (`hcdf/dom.pyi`), exposed for runtime introspection and the drift test.
#[pyfunction]
pub fn dom_pyi() -> String {
    dom_pyi_text()
}

// ── registration ────────────────────────────────────────────────────────────────────────────────

/// Register the generated DOM pyclasses (+ the data-enum companion + the stub accessor).
pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    generated::register_generated(m)?;
    stream_profile_generated::register_generated(m)?;
    m.add_class::<PyVisualAppearance>()?;
    m.add_function(wrap_pyfunction!(dom_pyi, m)?)?;
    Ok(())
}
