// @generated by hcdformat-domgen. DO NOT EDIT.
// Regenerate with: scripts/generate_dom_mirrors.sh (drift-checked in CI).
//
// One mirror per reachable model struct or choice; the `hcdformat-pyderive` attribute macros
// expand each into a write-through Python DOM handle. Each mirror's site list is every
// parent that references the type (the locator-enum variants); shared types (Pose, Color,
// geometry, …) therefore carry several sites. See hcdformat-pyderive/src/lib.rs.

use super::generated::DomEnum;
use super::{err, resolve_index, stale, Resolve};
use hcdformat::model::connectivity::QualifiedId;
use hcdformat::model::*;
use hcdformat_pyderive::pydom;
use pyo3::prelude::*;

#[pydom(py = PyStreamProfileConnectivityFunctionRef, target = ConnectivityFunctionRef, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamForwarding, ptype = StreamForwarding, field = function, card = req),
)]
struct ConnectivityFunctionRefDom {
    component: String,
    function: String,
    #[pydom(nested = PyStreamProfileInstanceRef)]
    instance: Option<()>,
}

#[pydom(py = PyFrer, target = Frer, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamDefinition, ptype = StreamDefinition, field = frer, card = opt),
)]
struct FrerDom {
    #[pydom(required_scalar)]
    seamless_trees: u32,
    #[pydom(mapped_enum)]
    sequence_encoding: (),
}

#[pydom(py = PyStreamProfileInstanceRef, target = InstanceRef, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamProfileConnectivityFunctionRef, ptype = ConnectivityFunctionRef, field = instance, card = opt),
    site(parent = PyStreamProfileNetworkRef, ptype = NetworkRef, field = instance, card = opt),
    site(parent = PyStreamProfileParticipantRef, ptype = ParticipantRef, field = instance, card = opt),
    site(parent = PyStreamProfileScheduleRef, ptype = ScheduleRef, field = instance, card = opt),
    site(parent = PyStreamGroupRef, ptype = StreamGroupRef, field = instance, card = opt),
    site(parent = PyStreamProfileTrafficClassRef, ptype = TrafficClassRef, field = instance, card = opt),
)]
struct InstanceRefDom {
    #[pydom(list = PyStreamProfileInstanceSegment, name_field = opt, clone_list)]
    segment: Vec<()>,
}

#[pydom(py = PyStreamProfileInstanceSegment, target = InstanceSegment, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamProfileInstanceRef, ptype = InstanceRef, field = segment, card = vec),
)]
struct InstanceSegmentDom {
    name: Option<String>,
    #[pydom(required_scalar)]
    occurrence: u32,
}

#[pydom(py = PyStreamProfileNetworkRef, target = NetworkRef, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamPath, ptype = StreamPath, field = network, card = vec),
)]
struct NetworkRefDom {
    network: String,
    #[pydom(nested = PyStreamProfileInstanceRef)]
    instance: Option<()>,
}

#[pydom(py = PyStreamProfileParticipantRef, target = ParticipantRef, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamForwardingEnd, ptype = StreamForwardingEnd, field = participant, card = req),
    site(parent = PyStreamListener, ptype = StreamListener, field = participant, card = req),
    site(parent = PyStreamTalker, ptype = StreamTalker, field = participant, card = req),
)]
struct ParticipantRefDom {
    network: String,
    participant: String,
    #[pydom(nested = PyStreamProfileInstanceRef)]
    instance: Option<()>,
}

#[pydom(py = PyStreamProfileScheduleRef, target = ScheduleRef, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamDefinition, ptype = StreamDefinition, field = schedule_ref, card = opt),
)]
struct ScheduleRefDom {
    network: String,
    schedule: String,
    #[pydom(nested = PyStreamProfileInstanceRef)]
    instance: Option<()>,
}

#[pydom(py = PyStreamDefinition, target = StreamDefinition, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamProfileDocument, ptype = StreamProfileDocument, field = stream, card = vec),
)]
struct StreamDefinitionDom {
    name: String,
    vlan_id: Option<u16>,
    pcp: Option<u8>,
    #[pydom(required_scalar)]
    max_frame_size_bytes: u32,
    #[pydom(required_scalar)]
    interval_ns: u64,
    max_latency_ns: Option<u64>,
    #[pydom(validated_string)]
    protocol: Option<QualifiedId>,
    description: Option<String>,
    #[pydom(nested = PyStreamGroupRef, clone_nested)]
    group_ref: Option<()>,
    #[pydom(required_nested = PyStreamPath)]
    path: (),
    #[pydom(required_nested = PyStreamTalker)]
    talker: (),
    #[pydom(list = PyStreamListener, name_field = none, clone_list)]
    listener: Vec<()>,
    #[pydom(nested = PyStreamProfileTrafficClassRef, clone_nested)]
    traffic_class_ref: Option<()>,
    #[pydom(nested = PyStreamProfileScheduleRef, clone_nested)]
    schedule_ref: Option<()>,
    #[pydom(nested = PyFrer, clone_nested)]
    frer: Option<()>,
}

#[pydom(py = PyStreamForwarding, target = StreamForwarding, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamPath, ptype = StreamPath, field = forwarding, card = vec),
)]
struct StreamForwardingDom {
    #[pydom(name = "from_")]
    #[pydom(required_nested = PyStreamForwardingEnd)]
    from: (),
    #[pydom(required_nested = PyStreamProfileConnectivityFunctionRef)]
    function: (),
    #[pydom(required_nested = PyStreamForwardingEnd)]
    to: (),
}

#[pydom(py = PyStreamForwardingEnd, target = StreamForwardingEnd, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamForwarding, ptype = StreamForwarding, field = from, card = req),
    site(parent = PyStreamForwarding, ptype = StreamForwarding, field = to, card = req),
)]
struct StreamForwardingEndDom {
    #[pydom(required_nested = PyStreamProfileParticipantRef)]
    participant: (),
}

#[pydom(py = PyStreamGroup, target = StreamGroup, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamProfileDocument, ptype = StreamProfileDocument, field = stream_group, card = vec),
)]
struct StreamGroupDom {
    name: String,
    description: Option<String>,
}

#[pydom(py = PyStreamGroupRef, target = StreamGroupRef, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamDefinition, ptype = StreamDefinition, field = group_ref, card = opt),
)]
struct StreamGroupRefDom {
    group: String,
    #[pydom(nested = PyStreamProfileInstanceRef)]
    instance: Option<()>,
}

#[pydom(py = PyStreamListener, target = StreamListener, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamDefinition, ptype = StreamDefinition, field = listener, card = vec),
)]
struct StreamListenerDom {
    #[pydom(required_nested = PyStreamProfileParticipantRef)]
    participant: (),
}

#[pydom(py = PyStreamPath, target = StreamPath, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamDefinition, ptype = StreamDefinition, field = path, card = req),
)]
struct StreamPathDom {
    #[pydom(list = PyStreamProfileNetworkRef, name_field = none, clone_list)]
    network: Vec<()>,
    #[pydom(list = PyStreamForwarding, name_field = none, clone_list)]
    forwarding: Vec<()>,
}

#[pydom(py = PyStreamProfileDependency, target = StreamProfileDependency, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamProfileDocument, ptype = StreamProfileDocument, field = dependency, card = vec),
)]
struct StreamProfileDependencyDom {
    uri: String,
    sha: Option<String>,
    #[pydom(required_scalar)]
    required: bool,
}

#[pydom(py = PyStreamProfileDocument, target = StreamProfileDocument, owner(target = StreamProfileDocument, py = PyStreamProfileDocument), root)]
struct StreamProfileDocumentDom {
    name: String,
    version: String,
    description: Option<String>,
    #[pydom(list = PyStreamProfileDependency, name_field = none, clone_list)]
    dependency: Vec<()>,
    #[pydom(list = PyStreamGroup, name_field = req, clone_list)]
    stream_group: Vec<()>,
    #[pydom(list = PyStreamDefinition, name_field = req, clone_list)]
    stream: Vec<()>,
}

#[pydom(py = PyStreamTalker, target = StreamTalker, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamDefinition, ptype = StreamDefinition, field = talker, card = req),
)]
struct StreamTalkerDom {
    #[pydom(required_nested = PyStreamProfileParticipantRef)]
    participant: (),
}

#[pydom(py = PyStreamProfileTrafficClassRef, target = TrafficClassRef, owner(target = StreamProfileDocument, py = PyStreamProfileDocument),
    site(parent = PyStreamDefinition, ptype = StreamDefinition, field = traffic_class_ref, card = opt),
)]
struct TrafficClassRefDom {
    network: String,
    traffic_class: String,
    #[pydom(nested = PyStreamProfileInstanceRef)]
    instance: Option<()>,
}

/// Register every generated DOM pyclass on the `hcdf` extension module.
pub fn register_generated(m: &pyo3::Bound<'_, pyo3::types::PyModule>) -> pyo3::PyResult<()> {
    __register_py_stream_profile_connectivity_function_ref(m)?;
    __register_py_frer(m)?;
    __register_py_stream_profile_instance_ref(m)?;
    __register_py_stream_profile_instance_segment(m)?;
    __register_py_stream_profile_network_ref(m)?;
    __register_py_stream_profile_participant_ref(m)?;
    __register_py_stream_profile_schedule_ref(m)?;
    __register_py_stream_definition(m)?;
    __register_py_stream_forwarding(m)?;
    __register_py_stream_forwarding_end(m)?;
    __register_py_stream_group(m)?;
    __register_py_stream_group_ref(m)?;
    __register_py_stream_listener(m)?;
    __register_py_stream_path(m)?;
    __register_py_stream_profile_dependency(m)?;
    __register_py_stream_profile_document(m)?;
    __register_py_stream_talker(m)?;
    __register_py_stream_profile_traffic_class_ref(m)?;
    Ok(())
}

/// The concatenated `.pyi` stub for every generated handle + its list sub-handles.
pub fn pyi_generated() -> String {
    let mut s = String::new();
    s.push_str(__pyi_py_stream_profile_connectivity_function_ref());
    s.push('\n');
    s.push_str(__pyi_py_frer());
    s.push('\n');
    s.push_str(__pyi_py_stream_profile_instance_ref());
    s.push('\n');
    s.push_str(__pyi_py_stream_profile_instance_segment());
    s.push('\n');
    s.push_str(__pyi_py_stream_profile_network_ref());
    s.push('\n');
    s.push_str(__pyi_py_stream_profile_participant_ref());
    s.push('\n');
    s.push_str(__pyi_py_stream_profile_schedule_ref());
    s.push('\n');
    s.push_str(__pyi_py_stream_definition());
    s.push('\n');
    s.push_str(__pyi_py_stream_forwarding());
    s.push('\n');
    s.push_str(__pyi_py_stream_forwarding_end());
    s.push('\n');
    s.push_str(__pyi_py_stream_group());
    s.push('\n');
    s.push_str(__pyi_py_stream_group_ref());
    s.push('\n');
    s.push_str(__pyi_py_stream_listener());
    s.push('\n');
    s.push_str(__pyi_py_stream_path());
    s.push('\n');
    s.push_str(__pyi_py_stream_profile_dependency());
    s.push('\n');
    s.push_str(__pyi_py_stream_profile_document());
    s.push('\n');
    s.push_str(__pyi_py_stream_talker());
    s.push('\n');
    s.push_str(__pyi_py_stream_profile_traffic_class_ref());
    s.push('\n');
    s
}
