//! Vendored, sha-pinned official HCDF artifacts (frozen 1.0).
//!
//! The pin constants below are GENERATED by `build.rs` from the vendored `HASHES` (single source of
//! truth) and verified at build time. Runtime verification is also available for embedded bytes.
//! Per the hcdformat contract: bind to versioned artifacts by content hash, never by filename or a
//! version string alone.
use crate::error::Result;

// e.g. HCDF_XSD_SHA256_1_0 and REGISTRIES_CONNECTIVITY_PROFILES_JSON_SHA256_1_0; generated from HASHES.
include!(concat!(env!("OUT_DIR"), "/schema_pins.rs"));

/// The frozen 1.0 schema bytes, embedded for hermetic native/offline use and runtime re-verification.
///
/// On native this is always embedded (offline use + runtime re-hash). On wasm the 300+ KB are carried
/// ONLY when the `xsd` feature is enabled; then the pure-Rust [`crate::xsd::validate_xsd`] (uppsala)
/// needs them to validate IN the browser. With the default/no-`xsd` wasm build nothing consumes the
/// bytes, so they stay out and only the hash const is carried (the build-time pin is the trust root).
#[cfg(any(not(target_arch = "wasm32"), feature = "xsd", feature = "json"))]
pub const HCDF_XSD_1_0: &[u8] = include_bytes!("../assets/schema/hcdf/1.0/hcdf.xsd");

/// The frozen 1.0 stream-profile sidecar schema bytes.
///
/// It follows the same embedding policy as the core schema, so sidecar validation is hermetic on
/// native and in a browser with the xsd feature enabled.
#[cfg(any(not(target_arch = "wasm32"), feature = "xsd"))]
pub const HCDF_STREAM_PROFILE_XSD_1_0: &[u8] =
    include_bytes!("../assets/schema/hcdf/1.0/hcdf-stream-profile.xsd");

/// The canonical built-in connectivity profile registry, embedded on native and WASM.
pub const CONNECTIVITY_PROFILES_JSON_1_0: &[u8] =
    include_bytes!("../assets/schema/hcdf/1.0/registries/connectivity-profiles.json");

/// The registry's JSON Schema, embedded on native and WASM for offline tooling.
pub const CONNECTIVITY_PROFILE_REGISTRY_SCHEMA_JSON_1_0: &[u8] = include_bytes!(
    "../assets/schema/hcdf/1.0/registries/connectivity-profile-registry.schema.json"
);

/// Re-hash the embedded core and stream-profile schemas and confirm they match their build-time pins.
/// A default wasm build carries neither byte array and this is a no-op there. A wasm build with xsd
/// verifies the same embedded bytes used by both validators. The JSON-only wasm feature embeds and
/// verifies only the core schema it consumes.
pub fn verify_embedded_schema() -> Result<()> {
    #[cfg(any(not(target_arch = "wasm32"), feature = "xsd", feature = "json"))]
    {
        use crate::error::Error;
        use sha2::{Digest, Sha256};
        let got = format!("{:x}", Sha256::digest(HCDF_XSD_1_0));
        if got != HCDF_XSD_SHA256_1_0 {
            return Err(Error::SchemaShaMismatch {
                expected: HCDF_XSD_SHA256_1_0,
                got,
            });
        }
    }
    #[cfg(any(not(target_arch = "wasm32"), feature = "xsd"))]
    {
        use crate::error::Error;
        use sha2::{Digest, Sha256};
        let got = format!("{:x}", Sha256::digest(HCDF_STREAM_PROFILE_XSD_1_0));
        if got != HCDF_STREAM_PROFILE_XSD_SHA256_1_0 {
            return Err(Error::SchemaShaMismatch {
                expected: HCDF_STREAM_PROFILE_XSD_SHA256_1_0,
                got,
            });
        }
    }
    Ok(())
}

/// Re-hash the registry and its JSON Schema against the versioned build-time pins.
pub fn verify_embedded_connectivity_registry() -> Result<()> {
    use crate::error::Error;
    use sha2::{Digest, Sha256};
    for (bytes, expected) in [
        (
            CONNECTIVITY_PROFILES_JSON_1_0,
            REGISTRIES_CONNECTIVITY_PROFILES_JSON_SHA256_1_0,
        ),
        (
            CONNECTIVITY_PROFILE_REGISTRY_SCHEMA_JSON_1_0,
            REGISTRIES_CONNECTIVITY_PROFILE_REGISTRY_SCHEMA_JSON_SHA256_1_0,
        ),
    ] {
        let got = format!("{:x}", Sha256::digest(bytes));
        if got != expected {
            return Err(Error::SchemaShaMismatch { expected, got });
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use sha2::{Digest, Sha256};
    use std::path::PathBuf;

    /// The repo root: this crate lives at `<repo>/rust/hcdformat-rs`, the `versions/` archive under `<repo>`.
    fn repo_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
    }

    fn sha256_hex(bytes: &[u8]) -> String {
        format!("{:x}", Sha256::digest(bytes))
    }

    /// Parse `versions/HASHES` into `(version, file, sha)` rows, skipping blank / `#`-comment lines. A
    /// non-3-field row is a malformed archive index: a hard failure, exactly as the Python raised.
    fn parse_hashes(text: &str) -> Vec<(String, String, String)> {
        let mut rows = Vec::new();
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let parts: Vec<&str> = line.split_whitespace().collect();
            assert_eq!(parts.len(), 3, "malformed HASHES line: {line:?}");
            rows.push((
                parts[0].to_string(),
                parts[1].to_string(),
                parts[2].to_string(),
            ));
        }
        rows
    }

    /// The `@version` default declared by the root `hcdf.xsd` (Python `declared_version`'s
    /// `<xs:attribute name="version" ... default="([0-9.]+)">` scan, done without a regex dep). The XSD
    /// carries several `version` attributes (USB/LIN protocol versions, …); like `re.search`, this
    /// returns the FIRST whose tag also carries a NUMERIC `default="..."`: the root `@version`.
    fn declared_version(xsd: &str) -> String {
        let needle = r#"<xs:attribute name="version""#;
        let key = r#"default=""#;
        let mut from = 0;
        while let Some(rel) = xsd[from..].find(needle) {
            let anchor = from + rel;
            let tag_end = anchor
                + xsd[anchor..]
                    .find('>')
                    .expect("version attribute tag closes");
            let tag = &xsd[anchor..tag_end];
            if let Some(ks) = tag.find(key) {
                let rest = &tag[ks + key.len()..];
                if let Some(end) = rest.find('"') {
                    let ver = &rest[..end];
                    if !ver.is_empty() && ver.chars().all(|c| c.is_ascii_digit() || c == '.') {
                        return ver.to_string();
                    }
                }
            }
            from = anchor + needle.len();
        }
        panic!("root hcdf.xsd has no version attribute with a numeric default");
    }

    /// The `versions/` frozen-archive + hash-pin invariants, the pure-Rust port of the retired
    /// `scripts/check_version_hashes.py`, moved into `cargo test` so the archive is gated with no Python:
    ///   1. every `HASHES` row's frozen copy `versions/<v>/<file>` exists and matches its sha256;
    ///   2. the root-declared `@version` has a `versions/<v>/` archive in `HASHES`;
    ///   3. each live canonical versioned artifact byte-matches the archive copy for the declared
    ///      version.
    ///
    /// "Same version string, different bytes" is therefore a hard, detectable contradiction rather than
    /// a silent drift. Skips cleanly when `versions/` is not reachable (e.g. a packaged crate tarball).
    #[test]
    fn versions_archive_matches_hashes() {
        let root = repo_root();
        let Ok(hashes_text) = std::fs::read_to_string(root.join("versions/HASHES")) else {
            eprintln!("skipping: versions/HASHES not reachable (packaged crate)");
            return;
        };
        let rows = parse_hashes(&hashes_text);
        assert!(!rows.is_empty(), "versions/HASHES has no archive entries");

        // (1) frozen-archive integrity: each recorded copy exists and hashes to its pin.
        for (version, fname, expected) in &rows {
            let frozen = root.join("versions").join(version).join(fname);
            let bytes = std::fs::read(&frozen).unwrap_or_else(|e| {
                panic!("missing frozen archive versions/{version}/{fname}: {e}")
            });
            assert_eq!(
                &sha256_hex(&bytes),
                expected,
                "frozen archive changed: versions/{version}/{fname}"
            );
        }

        // (2) the root-declared version must have an archive.
        let root_xsd = std::fs::read_to_string(root.join("hcdf.xsd")).expect("read root hcdf.xsd");
        let ver = declared_version(&root_xsd);
        assert!(
            rows.iter().any(|(v, _, _)| v == &ver),
            "root hcdf @version={ver:?} has no versions/{ver}/ archive in HASHES"
        );

        // (3) live canonical artifacts must equal the archive for the declared version.
        for fname in [
            "hcdf.xsd",
            "hcdf-stream-profile.xsd",
            "registries/connectivity-profiles.json",
            "registries/connectivity-profile-registry.schema.json",
        ] {
            let Ok(bytes) = std::fs::read(root.join(fname)) else {
                continue;
            };
            let expected = rows
                .iter()
                .find(|(v, f, _)| v == &ver && f == fname)
                .map(|(_, _, s)| s.as_str())
                .unwrap_or_else(|| panic!("no HASHES entry for live {fname} at version {ver}"));
            assert_eq!(
                sha256_hex(&bytes),
                expected,
                "live {fname} drifted from its {ver} archive (update versions/{ver}/{fname} + HASHES on an intentional release)"
            );
        }
    }

    #[test]
    fn registry_distribution_copies_are_byte_identical() {
        let root = repo_root();
        let canonical_root = root.join("registries");
        if !canonical_root.is_dir() {
            eprintln!("skipping: repository registry sources not reachable (packaged crate)");
            return;
        }
        let artifacts = [
            "connectivity-profiles.json",
            "connectivity-profile-registry.schema.json",
        ];
        for artifact in artifacts {
            let canonical = std::fs::read(canonical_root.join(artifact)).unwrap_or_else(|error| {
                panic!("read canonical registry artifact {artifact}: {error}")
            });
            for copy in [
                root.join("versions/1.0/registries").join(artifact),
                root.join("rust/hcdformat-rs/assets/schema/hcdf/1.0/registries")
                    .join(artifact),
                root.join("rust/hcdformat-py/wheel-data/data/share/hcdformat/registries")
                    .join(artifact),
            ] {
                let bytes = std::fs::read(&copy).unwrap_or_else(|error| {
                    panic!(
                        "read registry distribution copy {}: {error}",
                        copy.display()
                    )
                });
                assert_eq!(
                    bytes,
                    canonical,
                    "registry copy drifted: {}",
                    copy.display()
                );
            }
        }
        assert_eq!(
            std::fs::read(root.join("versions/HASHES")).expect("read release HASHES"),
            std::fs::read(root.join("rust/hcdformat-rs/assets/schema/hcdf/1.0/HASHES"))
                .expect("read vendored HASHES"),
            "vendored HASHES drifted from versions/HASHES"
        );
    }

    #[test]
    fn schema_distribution_copies_are_byte_identical() {
        let root = repo_root();
        for artifact in ["hcdf.xsd", "hcdf-stream-profile.xsd"] {
            let Ok(canonical) = std::fs::read(root.join(artifact)) else {
                eprintln!("skipping: repository schema sources not reachable (packaged crate)");
                return;
            };
            for copy in [
                root.join("versions/1.0").join(artifact),
                root.join("rust/hcdformat-rs/assets/schema/hcdf/1.0")
                    .join(artifact),
                root.join("rust/hcdformat-py/wheel-data/data/share/hcdformat")
                    .join(artifact),
            ] {
                let bytes = std::fs::read(&copy).unwrap_or_else(|error| {
                    panic!("read schema distribution copy {}: {error}", copy.display())
                });
                assert_eq!(
                    bytes,
                    canonical,
                    "schema distribution copy drifted: {}",
                    copy.display()
                );
            }
        }
    }

    #[test]
    fn derived_distribution_copies_are_byte_identical() {
        let root = repo_root();
        for artifact in ["hcdf.schema.json", "hcdf.completions.json"] {
            let Ok(canonical) = std::fs::read(root.join(artifact)) else {
                eprintln!(
                    "skipping: repository derived schema sources not reachable (packaged crate)"
                );
                return;
            };
            let copy = root
                .join("rust/hcdformat-py/wheel-data/data/share/hcdformat")
                .join(artifact);
            let bytes = std::fs::read(&copy).unwrap_or_else(|error| {
                panic!(
                    "read derived schema distribution copy {}: {error}",
                    copy.display()
                )
            });
            assert_eq!(
                bytes,
                canonical,
                "derived schema distribution copy drifted: {}",
                copy.display()
            );
        }
    }
}
