//! Compile-time schema sha-pin verification, single-sourced from the vendored `HASHES` file.
//!
//! The official hcdformat repo's contract (docs/design/versioning.md) is: bind to a versioned artifact
//! by its content hash, never by filename or the version string. We vendor the frozen artifacts plus
//! a copy of `versions/HASHES`, then here re-hash each vendored file and assert it equals its HASHES
//! pin: a corrupted or swapped artifact fails the build. The pin constants consumed at runtime
//! are GENERATED from HASHES (one source of truth), never hand-copied.
use sha2::{Digest, Sha256};
use std::{collections::BTreeMap, env, fs, path::Path};

#[path = "src/schema_build_support.rs"]
mod schema_build_support;

use schema_build_support::{reserve_schema_const, safe_relative_schema_path};

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let base = Path::new(&manifest).join("assets/schema/hcdf/1.0");
    let hashes_path = base.join("HASHES");
    println!("cargo:rerun-if-changed={}", hashes_path.display());

    let hashes = fs::read_to_string(&hashes_path).expect("vendored HASHES missing");
    let mut generated = String::from(
        "// @generated by build.rs from assets/schema/hcdf/1.0/HASHES. Do not edit.\n",
    );
    let mut constants = BTreeMap::new();

    for line in hashes.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let f: Vec<&str> = line.split_whitespace().collect();
        assert_eq!(f.len(), 3, "malformed HASHES line: {line:?}");
        let (version, file, expected) = (f[0], f[1], f[2]);

        let relative = safe_relative_schema_path(file)
            .unwrap_or_else(|error| panic!("invalid schema path in HASHES: {error}"));
        let p = base.join(relative);
        println!("cargo:rerun-if-changed={}", p.display());
        let bytes = fs::read(&p).unwrap_or_else(|_| panic!("vendored artifact {file} missing"));
        let got = format!("{:x}", Sha256::digest(&bytes));
        assert_eq!(
            got, expected,
            "vendored {file} sha256 mismatch: got {got}, expected {expected} (HASHES v{version}); \
             re-sync from hcdformat versions/HASHES"
        );
        let ident = reserve_schema_const(&mut constants, file, version)
            .unwrap_or_else(|error| panic!("invalid schema pin in HASHES: {error}"));
        generated.push_str(&format!("pub const {ident}: &str = \"{expected}\";\n"));
    }

    let out = Path::new(&env::var("OUT_DIR").unwrap()).join("schema_pins.rs");
    fs::write(&out, generated).expect("write schema_pins.rs");
}
