# AUTO-GENERATED by hcdformat-py: run
#   cargo run --manifest-path rust/hcdformat-py/Cargo.toml --bin gen_pyi
# Do not edit by hand.
from typing import Optional

from .assets import Baker
from .dom import Hcdf
from .urdf import LossManifest

def from_sdf(src: object, baker: Optional[Baker] = ...) -> tuple[Hcdf, list[str]]: ...
def to_sdf(doc: Hcdf) -> tuple[str, LossManifest]: ...
